-- Creamos la DB
DROP DATABASE IF EXIST "Game";
CREATE DATABASE IF NOT EXIST "Game";
USE "Game";
--- Creando las tablas
DROP TABLE IF EXIST "ACC";
CREATE TABLE IF NOT EXIST "ACC" (
  "ID_ACCOUNT" INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  "ID_ACC_LVL" INT NOT NULL UNIQUE,
  "USER" VARCHAR(50) NOT NULL PRIMARY KEY,
  "PWR" VARCHAR(20) NOT NULL PRIMARY KEY,
  "EMAIL" VARCHAR(50) NOT NULL PRIMARY KEY,
  FOREIGN KEY ("ID_ACC_LVL") REFERENCES ACC_LVL ("ID_ACC_LVL")
);

DROP TABLE IF EXIST "ACC_FORO";
CREATE TABLE IF NOT EXIST "ACC_FORO" (
  "ID_ACCOUNT" INT NOT NULL UNIQUE AUTO_INCREMENT,
  "ID_ACC_LVL_F" INT NOT NULL UNIQUE,
  "USER" VARCHAR(50) NOT NULL,
  "PWR" VARCHAR(20) NOT NULL,
  "EMAIL" VARCHAR(50) NOT NULL,
  FOREIGN KEY ("ID_ACCOUNT") REFERENCES ACC ("ID_ACCOUNT"),
  FOREIGN KYE ("ID_ACC_LVL_F") REFERENCES ACC_LVL_FORO ("ID_ACC_LVL_F"),
  FOREIGN KEY ("USER") REFERENCES ACC ("USER"),
  FOERING KEY ("PWR") REFERENCES ACC ("PWR"),
  FOERING KEY ("EMAIL") REFERENCES ACC ("EMAIL")
);

DROP TABLE IF EXIST "ACC_LVL";
CREATE TABLE IF NOT EXIST "ACC_LVL" (
  "ID_ACC_LVL" TINYINT NOT NULL UNIQUE PRIMARY KEY,
  "ADMIN" TINYINT,
  "MODERADOR" TINYINT,
  "GAMER" TINYINT,
  "BAN" TINYINT
);

DROP TABLE IF EXIST "ACC_LVL_FORO";
CREATE TABLE IF NOT EXIST "ACC_LVL_FORO" (
  "ID_ACC_LVL_F" TINYINT NOT NULL UNIQUE PRIMARY KEY,
  "ADMIN" TINYINT,
  "MODERADOR" TINYINT,
  "GAMER" TINYINT,
  "GUEST" TINYINT,
  "BAN" TINYINT
);

DROP TABLE IF EXIST "GAMER_LVL";
CREATE TABLE IF NOT EXIST "GAMER_LVL" (
  "ID_ACC_LVL_F" TINYINT NOT NULL UNIQUE,
  "LVL_1" TINYINT UNIQUE,
  "LVL_2" TINYINT UNIQUE,
  "LVL_3" TINYINT UNIQUE,
  FOERING KEY ("ID_ACC_LVL_F") REFERENCES ACC_LVL_FORO ("ID_ACC_LVL_F")
);

DROP TABLE IF EXIST "CHAR";
CREATE TABLE IF NOT EXIST "CHAR" (
  "ID_CHAR" INT NOT NULL UNIQUE AUTO_INCREMENT,
  "ID_ACC" INT NOT NULL UNIQUE,
  "ID_CLASS" INT NOT NULL UNIQUE,
  "ID_INFO" INT NOT NULL UNIQUE,
  "ID_BAG" INT NOT NULL UNIQUE,
  FOERING KEY ("ID_ACC") REFERENCES ACC ("ID_ACC"),
  FOERING KEY ("ID_CLASS") REFERENCES CLASS ("ID_CLASS"),
  FOERING KEY ("ID_INFO") REFERENCES INFO ("ID_INFO"),
  FOERING KEY ("ID_BAG") REFERENCES BAG ("ID_BAG")
);

DROP TABLE IF EXIST "BAG";
CREATE TABLE IF NOT EXIST "BAG" (
  "ID_BAG" INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  "ID_CHAR" INT NOT NULL UNIQUE,
  "ZENNY" INT DEFAULT "0",
  "EQUIP" INT,
  "CARD" INT,
  "CONSUME" INT,
  FOERING KEY ("ID_CHAR") REFERENCES CHAR ("ID_CHAR")
);

DROP TABLE IF EXIST "CLASS";
CREATE TABLE IF NOT EXIST "CLASS" (
  "ID_CLASS" TINYINT NOT NULL UNIQUE PRIMARY KEY,
  "NOVICE" TINYINT,
  "SWORDMAN" TINYINT,
  "THIEF" TINYINT,
  "ACOLYTE" TINYINT,
  "WIZZARD" TINYINT
);

DROP TABLE IF EXIST "CHAR_INFO";
CREATE TABLE IF NOT EXIST "CHAR_INFO" (
  "ID_CHAR" INT NOT NULL UNIQUE,
  "NAME" VARCHAR(20) NOT NULL UNIQUE,
  "LVL" INT NOT NULL,
  "STATS" INT NOT NULL,
  "ID_GUILD" INT UNIQUE,
  "BAN" INT UNIQUE,
  FOERING KEY ("ID_CHAR") REFERENCES CHAR ("ID_CHAR")
);

DROP TABLE IF EXIST "STATS";
CREATE TABLE IF NOT EXIST "STATS" (
  "ID_CHAR" INT NOT NULL UNIQUE,
  "MAX_HP" INT NOT NULL UNIQUE DEFAULT "500",
  "MAX_SP" INT NOT NULL UNIQUE DEFAULT "500",
  "STR" INT NOT NULL UNIQUE DEFAULT "1",
  "DEX" INT NOT NULL UNIQUE DEFAULT "1",
  "INT" INT NOT NULL UNIQUE DEFAULT "1",
  "AGI" INT NOT NULL UNIQUE DEFAULT "1",
  "VIT" INT NOT NULL UNIQUE DEFAULT "1",
  "LUK" INT NOT NULL UNIQUE DEFAULT "1",
  FOERING KEY ("ID_CHAR") REFERENCES CHAR ("ID_CHAR")
);
