-- Creamos la DB
DROP DATABASE IF EXISTS Game;
CREATE DATABASE IF NOT EXISTS Game;
USE Game;
--- Creando las tablas
DROP TABLE IF EXISTS ACC_LVL;
CREATE TABLE IF NOT EXISTS ACC_LVL (
  ID_ACC_LVL TINYINT NOT NULL UNIQUE PRIMARY KEY,
  GAMEMASTER TINYINT,
  MODERADOR TINYINT,
  GAMER TINYINT,
  BAN TINYINT
);

DROP TABLE IF EXISTS ACC_LVL_FORO;
CREATE TABLE IF NOT EXISTS ACC_LVL_FORO (
  ID_ACC_LVL_F TINYINT NOT NULL UNIQUE PRIMARY KEY,
  GAMEMASTER TINYINT,
  MODERADOR TINYINT,
  GAMER TINYINT,
  GUEST TINYINT,
  BAN TINYINT
);

DROP TABLE IF EXISTS BAG;
CREATE TABLE IF NOT EXISTS BAG (
  ID_BAG INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  ID_CHAR INT NOT NULL UNIQUE,
  ZENNY INT DEFAULT "0",
  EQUIP INT,
  CARD INT,
  CONSUME INT,
  FOREIGN KEY (ID_CHAR) REFERENCES CHARS (ID_CHAR)
);

DROP TABLE IF EXISTS CLASS;
CREATE TABLE IF NOT EXISTS CLASS (
  ID_CLASS TINYINT NOT NULL UNIQUE PRIMARY KEY,
  NOVICE TINYINT,
  SWORDMAN TINYINT,
  THIEF TINYINT,
  ACOLYTE TINYINT,
  WIZZARD TINYINT
);

DROP TABLE IF EXISTS CHAR_INFO;
CREATE TABLE IF NOT EXISTS CHAR_INFO (
  ID_CHAR INT NOT NULL UNIQUE,
  NAME VARCHAR(20) NOT NULL UNIQUE,
  LVL INT NOT NULL,
  STATS INT NOT NULL,
  ID_GUILD INT UNIQUE,
  BAN INT UNIQUE,
  FOREIGN KEY (ID_CHAR) REFERENCES CHARS (ID_CHAR)
);

DROP TABLE IF EXISTS STATS;
CREATE TABLE IF NOT EXISTS STATS (
  ID_CHAR INT NOT NULL UNIQUE,
  MAX_HP INT NOT NULL UNIQUE DEFAULT "500",
  MAX_SP INT NOT NULL UNIQUE DEFAULT "500",
  STR INT NOT NULL UNIQUE DEFAULT "1",
  DEX INT NOT NULL UNIQUE DEFAULT "1",
  INTELIGENCE INT NOT NULL UNIQUE DEFAULT "1",
  AGI INT NOT NULL UNIQUE DEFAULT "1",
  VIT INT NOT NULL UNIQUE DEFAULT "1",
  LUK INT NOT NULL UNIQUE DEFAULT "1",
  FOREIGN KEY (ID_CHAR) REFERENCES CHARS (ID_CHAR)
);

DROP TABLE IF EXISTS ACC;
CREATE TABLE IF NOT EXISTS ACC (
  ID_ACCOUNT INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  ID_ACC_LVL INT NOT NULL UNIQUE,
  USERS VARCHAR(50) NOT NULL,
  PWR VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  FOREIGN KEY (ID_ACC_LVL) REFERENCES ACC_LVL (ID_ACC_LVL)
);

DROP TABLE IF EXISTS ACC_FORO;
CREATE TABLE IF NOT EXISTS ACC_FORO (
  ID_ACCOUNT INT NOT NULL UNIQUE AUTO_INCREMENT,
  ID_ACC_LVL_F INT NOT NULL UNIQUE,
  USERS VARCHAR(50) NOT NULL,
  PWR VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  FOREIGN KEY (ID_ACCOUNT) REFERENCES ACC (ID_ACCOUNT),
  FOREIGN KEY (ID_ACC_LVL_F) REFERENCES ACC_LVL_FORO (ID_ACC_LVL_F),
  FOREIGN KEY (USER) REFERENCES ACC (USER),
  FOREIGN KEY (PWR) REFERENCES ACC (PWR),
  FOREIGN KEY (EMAIL) REFERENCES ACC (EMAIL)
);

DROP TABLE IF EXISTS GAMER_LVL;
CREATE TABLE IF NOT EXISTS GAMER_LVL (
  ID_ACC_LVL_F TINYINT NOT NULL UNIQUE,
  LVL_1 TINYINT UNIQUE,
  LVL_2 TINYINT UNIQUE,
  LVL_3 TINYINT UNIQUE,
  FOREIGN KEY (ID_ACC_LVL_F) REFERENCES ACC_LVL_FORO (ID_ACC_LVL_F)
);

DROP TABLE IF EXISTS CHARS;
CREATE TABLE IF NOT EXISTS CHARS (
  ID_CHAR INT NOT NULL UNIQUE AUTO_INCREMENT,
  ID_ACC INT NOT NULL UNIQUE,
  ID_CLASS INT NOT NULL UNIQUE,
  ID_INFO INT NOT NULL UNIQUE,
  ID_BAG INT NOT NULL UNIQUE,
  FOREIGN KEY (ID_ACC) REFERENCES ACC (ID_ACC),
  FOREIGN KEY (ID_CLASS) REFERENCES CLASS (ID_CLASS),
  FOREIGN KEY (ID_INFO) REFERENCES INFO (ID_INFO),
  FOREIGN KEY (ID_BAG) REFERENCES BAG (ID_BAG)
);
